ROW_SIZE = 4
NUMBER_OPTIONS = 6
STARTING_LIVES = 6

FPS = 60

WIN_WIDTH, WIN_HEIGHT = 400, 500
CIRCLE_SIZE = 20 # diameter of counters
CIRCLE_SPACING = 2
BOTTOM_MARGIN = 30
TITLE_POSITION = (100, 100)
ROW_HEIGHT = CIRCLE_SIZE + 2 * CIRCLE_SPACING
TEXT_POSITION = WIN_HEIGHT - 3 * ROW_HEIGHT - 2 * CIRCLE_SPACING - BOTTOM_MARGIN

BG_COLOUR = (150, 150, 150)
COUNTER_BG = (0, 0, 0)
BLANK_COLOUR = (100, 100, 100)

TITLE_FONT = "cloisterblack"
TITLE_COLOUR = "purple"
GAME_FONT = "gabriola"
FONTCOLOUR = (0, 0, 0)
FONTSIZE = 20

BG_FILE = "background.jpg"
MUSIC_FILE = "mmtune.mid"
START_SOUND_FILE = "start.wav"
LOSE_SOUND_FILE = "lose.wav"
SELECT_SOUND_FILE = "blip.wav"
WIN_SOUND_FILE = "win.wav"